services:
  - type: web
    name: securesight-api
    env: node
    buildCommand: npm install
    startCommand: node api/server.js
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000